version: '3.7'
services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-dev
    environment:
      EULA: "true"
      MAX_MEMORY: 32G
      MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 15
      LEVEL_TYPE: AMPLIFIED
      MAX_PLAYERS: 100
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
